"""GitBranch sink: commit pack-repo changes to a branch + open a PR.

Runs after one or more Filesystem sinks have written assets. Detects
"nothing changed" and exits silently in that case (same upstream
version produced no diff).
"""

from __future__ import annotations

import logging
from pathlib import Path

from ichava_maintainer_toolkit.core import git
from ichava_maintainer_toolkit.core.config import interpolate
from ichava_maintainer_toolkit.core.pipeline import Sink, StageContext

logger = logging.getLogger(__name__)


class GitBranch(Sink):
    """Stage uncommitted changes, commit, push, optionally open a PR.

    Args:
        repo_root: path to the pack repo. May contain `{pack_root}`.
        branch: branch name. May contain `{version}`.
        commit_subject: subject template (`{pack}`, `{old}`, `{new}`).
        commit_body: body template (same tokens).
        open_pr: when True, run `gh pr create` after pushing.
        base: base branch for the PR. Defaults to `main`.
    """

    def __init__(
        self,
        *,
        repo_root: str | Path,
        branch: str = "chore/sync-upstream-{version}",
        commit_subject: str = "chore(upstream): bump {pack} to v{new}",
        commit_body: str = (
            "Automated sync from upstream {pack} {old} -> {new}.\n\n"
            "Generated by ichava/maintainer-toolkit. See documentation/icon-pack-maintainer-sync.md."
        ),
        open_pr: bool = True,
        base: str = "main",
    ) -> None:
        self.repo_root = str(repo_root)
        self.branch_template = branch
        self.subject_template = commit_subject
        self.body_template = commit_body
        self.open_pr_flag = open_pr
        self.base = base

    def execute(self, ctx: StageContext) -> StageContext:
        bindings = {
            "version": ctx.extras.get("fetched_version", ""),
            "pack_root": ctx.config.get("pack_root", ""),
            "pack": ctx.config.get("pack", ctx.pipeline_name),
            "old": ctx.config.get("old_version", "unknown"),
            "new": ctx.extras.get("fetched_version", ""),
        }
        repo = Path(interpolate(self.repo_root, **bindings)).resolve()

        if not git.has_uncommitted_changes(repo):
            logger.info("git-branch: no diff in %s -- skipping", repo)
            ctx.metrics.setdefault("sinks", {})["git_branch"] = {"status": "no-diff"}
            return ctx

        branch = interpolate(self.branch_template, **bindings)
        subject = interpolate(self.subject_template, **bindings)
        body = interpolate(self.body_template, **bindings)

        git.create_branch(repo, branch)
        sha = git.commit_all(repo, subject, body)
        git.push_branch(repo, branch)

        pr_url: str | None = None
        if self.open_pr_flag:
            pr_url = git.open_pr(repo, branch, subject, body, base=self.base)

        ctx.metrics.setdefault("sinks", {})["git_branch"] = {
            "status": "committed",
            "branch": branch,
            "sha": sha,
            "pr_url": pr_url,
        }
        ctx.extras["git_branch"] = branch
        ctx.extras["git_sha"] = sha
        if pr_url:
            ctx.extras["pr_url"] = pr_url
        logger.info("git-branch: committed %s on %s; PR=%s", sha[:8], branch, pr_url)
        return ctx
